#!/usr/bin/env bash
# Install and setup your load balancer.

sudo apt-get update
sudo apt-get -y install haproxy

frontend="\n\
frontend h_frontend\n\
    bind *:80\n\
    option forwardfor\n\
    default_backend h_backend"

backend="\n\
backend h_backend\n\
    balance roundrobin\n\
    server 2691-web-01 35.196.199.248:80 check\n\
    server 2691-web-02 3.88.139.97:80 check"

sudo echo -e "$frontend \n $backend" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
