#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes:
# - Display hours from 0 to 12.
# - Display minutes from 1 to 59.

h=1
m=1
while [ $h -le 12 ]
do
	m=1

	while [ $m -le 59 ]
	do
		echo "$m"
		(( m++ ))
	done

	echo "Hour: $h"
	(( h++ ))
done
