#!/usr/bin/env bash
# Displays:
# - The content of the current directory.
# - In a list format.
# - Where only the part of the name after the first dash is displayed.

export cmd=ls

for file in $($cmd)
do
	echo "$file" | cut -d "-" -f 2
done
